# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
-   repo: local
    hooks:
    -   id: update-requirements-txt
        name: update-requirements-txt
        description: 'Generate requirements.txt based on poetry.lock'
        entry: poetry
        args: [export, --format, requirements.txt, --output, requirements.txt]
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: update-requirements-dev-txt
        name: update-requirements-dev-txt
        description: 'Generate requirements-dev.txt based on poetry.lock'
        entry: poetry
        args: [export, --with, dev, --format, requirements.txt, --output, requirements-dev.txt]
        language: system
        pass_filenames: false
